nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173']
    allow_headers: ['Content-Type', 'Authorization', 'Accept']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:5173']